name = "name-my-baby"
pages_build_output_dir = ".vercel/output/static"

[vars]
ENVIRONMENT = "production"
API_SECRET = "Cola001"

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

[dev]
port = 3001

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "name-my-baby-db"
database_id = "0133574c-930a-4c62-92d3-9b7d58c6cb47"

# R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "name-my-baby-storage"
